version: '3'

services:
  api:
    container_name: python-workshop
    build: 'src'
    environment:
      PORT: 8088
      DB_HOST: database
      DB_USER: admin
      DB_PASSWD: admin
    depends_on:
      - database
    ports:
      - '8088:8088'
    restart: always

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: workshop_db
    ports:
      - '5432:5432'
